hello_server: hello_server.c
	g++ hello_server.c -o build/hello_server -g

hello_client: hello_client.c
	g++ hello_client.c -o build/hello_client -g

system_io: system_io.c
	g++ system_io.c -o build/system_io -g

file_io: file_io.c
	g++ file_io.c -o build/file_io -g