endian_conv: endian_conv.c
	g++ endian_conv.c -o build/endian_conv -g

inet_addr: inet_addr.c
	g++ inet_addr.c -o build/inet_addr -g

inet_aton: inet_aton.c
	g++ inet_aton.c -o build/inet_aton -g

inet_ntoa: inet_ntoa.c
	g++ inet_ntoa.c -o build/inet_ntoa -g
